name: Preprocessing Workflow

on:
  push:
    paths:
      - 'Bank_Personal_Loan.csv'
      - 'preprocessing/automate_Hardianto Tandi Seno.py'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  preprocess:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install pandas scikit-learn

    - name: Run preprocessing script
      run: python "preprocessing/automate_Hardianto Tandi Seno.py"

    - name: Commit and push result
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "github-actions"
        git add Bank_Personal_Loan/
        git commit -m "Auto-update preprocessed and split datasets" || echo "No changes to commit"
        git push
